Implement DB
yuriyoleynikov/MVCApp pull request #11
Opened 2016-11-07 18:04 UTC by yuriyoleynikov

#9

2016-11-09 20:47 UTC, Igorbek requested changes

2016-11-09 20:47 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Models/TodoItemTable.cs
> +    public class TodoItemTable
- `.Models` isn't a proper namespace for db data - move to `.Data`
- `TodoItemTable` doesn't sound well tho, rename to `TodoItem`

2016-11-09 20:47 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Startup.cs
> +            var connection = @"Server=(localdb)\mssqllocaldb;Database=TodoListApp;Trusted_Connection=True;";
use a setting instead, see how it's done for `ApplicationDbContext` below

2016-11-09 20:47 UTC, Igorbek commented on TodoListApp/tests/TodoListApp.Tests/InDatabaseRepositoryTests.cs
> +        private static DbContextOptions<MyDbContext> CreateNewContextOptions()
the next task will be to refactor tests to use the same code. just a heads-up

2016-11-09 20:47 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Data/MyDbContext.cs
> +    public class MyDbContext : DbContext
rename to something more meaningful, like `TodoListDbContext`

2016-11-09 20:47 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Migrations/MyDbContextModelSnapshot.cs
> +            modelBuilder.Entity("TodoListApp.Models.TodoItemTable", b =>
when you rename table, this will also need to be aligned with a new name

2016-11-10 15:27 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Migrations/MyDbContextModelSnapshot.cs
> +            modelBuilder.Entity("TodoListApp.Models.TodoItemTable", b =>
done

2016-11-10 15:28 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Data/MyDbContext.cs
> +    public class MyDbContext : DbContext
done

2016-11-10 15:30 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Models/TodoItemTable.cs
> +    public class TodoItemTable
done

2016-11-10 16:29 UTC, Igorbek approved these changes

2016-11-10 16:29 UTC, merged