Rename UI display names
yuriyoleynikov/MVCApp pull request #12
Opened 2016-11-11 16:43 UTC by yuriyoleynikov

Adress #10

2016-11-12 21:54 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Controllers/TodoController.cs
> +            return View(new TodoItemModel { Id = editModel.Id, Name = editModel.Name, Description = editModel.Description });
You can create a helper class with a method for converting from UI model to repository model. Also you can have opposite converter.

2016-11-14 12:19 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Controllers/TodoController.cs
> +            return View(new TodoItemModel { Id = editModel.Id, Name = editModel.Name, Description = editModel.Description });
Done.

2016-11-15 07:48 UTC, Igorbek requested changes
do not use `object`

2016-11-15 13:43 UTC, Igorbek approved these changes

2016-11-15 13:43 UTC, merged