First file implement.
yuriyoleynikov/MVCApp pull request #16
Opened 2016-11-24 06:40 UTC by yuriyoleynikov

Addresses #15

2016-11-25 16:32 UTC, Igorbek requested changes

2016-11-25 16:32 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                throw new KeyNotFoundException("Item was not found.");
temp file would not be deleted if an exception thrown here

2016-11-25 16:32 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                        willUpdate = true;
you don't have to move writing to the end. move it back

2016-11-25 16:32 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                throw new KeyNotFoundException("Item was not found.");
temp file wouldn't be deleted

2016-11-25 16:32 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                throw new KeyNotFoundException("Item was not found.");
BTW, use try-finally to make sure it will be removed always

2016-11-28 08:40 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                throw new KeyNotFoundException("Item was not found.");
Done.

2016-11-28 08:43 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                        willUpdate = true;
Done.

2016-11-28 08:44 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                throw new KeyNotFoundException("Item was not found.");
Done.

2016-11-28 16:30 UTC, Igorbek requested changes

2016-11-28 16:30 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +        public IEnumerable<TodoItem> GetTodoListByUserInner(string userId)
should be private

2016-11-28 16:30 UTC, Igorbek commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                        var _item = ReadTodoItem(stream);
naming! local vars must be camel-cased without underscore.

2016-11-29 08:10 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +        public IEnumerable<TodoItem> GetTodoListByUserInner(string userId)
Done.

2016-11-29 08:10 UTC, yuriyoleynikov commented on TodoListApp/src/TodoListApp/Models/InFileTodoListRepository.cs
> +                        var _item = ReadTodoItem(stream);
Done.

2016-11-29 16:14 UTC, Igorbek approved these changes

2016-11-29 16:15 UTC, merged